// Auto-generated by update.py — do not edit manually.
// Last updated: 2026-03-27 21:24 UTC

const MOCS_DATA = {
  "seasons": [
    {
      "id": "2026-s2",
      "label": "2026 Season 2",
      "year": 2026,
      "seasonNum": 2,
      "current": true,
      "start": "2026-03-25",
      "end": "2026-07-15",
      "showcaseFormats": [
        "Modern",
        "Legacy",
        "Standard",
        "Pauper"
      ],
      "rotatingFormat": "Pauper",
      "showcaseChallengesDates": [],
      "lastChanceDates": [],
      "showcaseQualifierDates": [],
      "showcaseOpenDates": [],
      "leaderboard": [],
      "notes": "Scheduled events restricted to players in certain geographic regions (Leagues and Queues unaffected)."
    },
    {
      "id": "2026-s1",
      "label": "2026 Season 1",
      "year": 2026,
      "seasonNum": 1,
      "current": false,
      "start": "2025-12-03",
      "end": "2026-03-25",
      "showcaseFormats": [
        "Modern",
        "Legacy",
        "Standard",
        "Vintage"
      ],
      "rotatingFormat": "Vintage",
      "showcaseChallengesDates": [],
      "lastChanceDates": [],
      "showcaseQualifierDates": [],
      "showcaseOpenDates": [],
      "leaderboard": [],
      "notes": ""
    }
  ],
  "structure": {
    "qpThreshold": 40,
    "championsShowcasePlayers": 8,
    "championsShowcasePrize": 50000,
    "worldsSeats": 2,
    "seasonsPerYear": 3
  }
};
