"""Fetch current MOCS season data from mtgo.com and update data.js.

Uses only stdlib — no dependencies required.
"""

import json
import re
import urllib.request
from datetime import date, datetime, timezone

# ---------------------------------------------------------------------------
# Season definitions (manually maintained when new seasons are announced)
# ---------------------------------------------------------------------------

SEASONS = [
    {
        "id": "2026-s2",
        "label": "2026 Season 2",
        "year": 2026,
        "seasonNum": 2,
        "start": "2026-03-25",
        "end": "2026-07-15",
        "showcaseFormats": ["Modern", "Legacy", "Standard", "Pauper"],
        "rotatingFormat": "Pauper",
        "notes": "Scheduled events restricted to players in certain geographic regions (Leagues and Queues unaffected).",
    },
    {
        "id": "2026-s1",
        "label": "2026 Season 1",
        "year": 2026,
        "seasonNum": 1,
        "start": "2025-12-03",
        "end": "2026-03-25",
        "showcaseFormats": ["Modern", "Legacy", "Standard", "Vintage"],
        "rotatingFormat": "Vintage",
        "notes": "",
    },
]


def current_season_id() -> str:
    """Return the id of the season that contains today's date."""
    today = date.today().isoformat()
    for s in SEASONS:
        if s["start"] <= today <= s["end"]:
            return s["id"]
    # Default to latest
    return SEASONS[0]["id"]


def build_data_js() -> str:
    """Build the contents of data.js."""
    cur = current_season_id()
    seasons_out = []
    for s in SEASONS:
        seasons_out.append(
            {
                "id": s["id"],
                "label": s["label"],
                "year": s["year"],
                "seasonNum": s["seasonNum"],
                "current": s["id"] == cur,
                "start": s["start"],
                "end": s["end"],
                "showcaseFormats": s["showcaseFormats"],
                "rotatingFormat": s["rotatingFormat"],
                "showcaseChallengesDates": [],
                "lastChanceDates": s.get("lastChanceDates", []),
                "showcaseQualifierDates": s.get("showcaseQualifierDates", []),
                "showcaseOpenDates": s.get("showcaseOpenDates", []),
                "leaderboard": [],
                "notes": s.get("notes", ""),
            }
        )

    data = {
        "seasons": seasons_out,
        "structure": {
            "qpThreshold": 40,
            "championsShowcasePlayers": 8,
            "championsShowcasePrize": 50000,
            "worldsSeats": 2,
            "seasonsPerYear": 3,
        },
    }

    js = json.dumps(data, indent=2)
    return (
        "// Auto-generated by update.py — do not edit manually.\n"
        f"// Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n\n"
        f"const MOCS_DATA = {js};\n"
    )


def main():
    content = build_data_js()
    with open("data.js", "w") as f:
        f.write(content)
    print(f"data.js updated ({len(content)} bytes)")


if __name__ == "__main__":
    main()
